config/routes.rb
BookInventory::Application.routes.draw do
  devise_for :users,  :only => :sessions do
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy", :as => :logout
  end
  
  root :to => 'books#index'

  
  resources :books do
    collection do
      post :comments
      get :authors
    end  
    get :author, :on => :member
  end
  
  match '/authors' => 'books#authors', :as => :authors
  match '/author' => 'books#author', :as => :author
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  # Add HABTM relation  with authors
  has_and_belongs_to_many :authors
  
  #comments
  acts_as_commentable
  
  
  attr_accessor :author_names
  
  validates :name, :presence => :true
  
  validates :author_names, :presence => :true
  
  validate :check_author_names
  
  before_create :add_authors
  
  
  #This method will make sure of valid author names
  def check_author_names
    if self.errors[:author_names].empty?
      inserted_author_name = self.author_names.split(',')
      inserted_author_name.collect!{|ia| ia.strip}      
      if inserted_author_name.empty? or inserted_author_name.include?("")
        self.errors.add(:author_names, 'are not entered properly. Please check again.')        
      else  
        for a_name in inserted_author_name
          if /[\,\"\?\!\;\:\#\$\%\&\(\)\*\+\-\/\<\>\=\@\[\]\\\^\_\{\}\|\~0-9]/.match(a_name)
            self.errors.add(:author_names, 'name should not contain any special characters or numbers.')
            return
          end
        end
      end
    end
  end
  
  #This method checks the duplicity of authors and book name. 
  #If book name with same authors exists then raise an error.
  #If they exist already then assign to the book. 
  #If not create them and assign to the book
  def add_authors
    authors_array = []
    fetched_authors_array = self.author_names.split(',')
    #downcase fetched authors name
    authors_array = fetched_authors_array.collect{|ia| ia.strip.downcase}
    #query to find uniqueness of authors
    existing_authors = Author.where("lower(name) in (?)", authors_array).includes(:books)
    name_duplicate_flag = self.is_name_duplicate?
    author_duplicate_flag = self.all_authors_are_same?(authors_array, existing_authors)
    if name_duplicate_flag and author_duplicate_flag
      for exist_author in existing_authors
        if exist_author.books.detect{|book| book.name.downcase == self.name.downcase}
          raise(InvalidBook,"Book already exists")
        end 
      end 
    end
    counter = 0
    for author_name in authors_array
      author = existing_authors.detect{|a| a.name.downcase == author_name}
      if author
        self.authors << author
      else
        #vlidation is skipped as its already checking for the things here. So saving query for uniqueness validation in authors
        self.authors << Author.new(:name => fetched_authors_array[counter])
      end
      counter += 1      
    end
  end
  
  #This method will check if book with same name is present or not. validates :name, :uniquenss => true cant be use. Because its scope with respect to authors to be checked
  #As its HABTM realationship...hook has to added manually to use itr in other method.
  def is_name_duplicate?
    Book.where("lower(name) in (?)", self.name.downcase) ? true : false 
  end
  
  #To check authirs are not same as existing book 
  def all_authors_are_same?(new_authors, existing_authors)
    flag = false
    for author_name in new_authors
      if existing_authors.detect{|e_name| e_name.name.downcase == author_name}
        flag = true
      else   
        flag = false
      end
    end
    flag
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_filter :check_authorization, :only => [:create,:new,:edit,:update,:destroy]
  
  def check_authorization
    authorize! :manage, @book || Book.new
  end 
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end
  
  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id], :include => [{:comments => :user}, :authors])
    @comments = @book.comments
    @authors = @book.authors

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end
  
  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end
  
  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end
  
  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    respond_to do |format|
      begin
        if @book.save
          format.html { redirect_to @book, notice: 'Book was successfully created.' }
          format.json { render json: @book, status: :created, location: @book }
        else
          format.html { render action: "new" }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      #This will take care of duplicate book entry in the scope of same authors only.  
      rescue InvalidBook => e
         @book.errors[:base] << e.to_s
         format.html { render action: "new" }
         format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    
    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
  
  def authors
    @authors = Author.all
    respond_to do |format|
      format.html
      format.json { render json: @authors }
    end
  end
  
  def author
    @author = Author.find(params[:id], :include => {:comments => :user})    
    @comments = @author.comments
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end    
  end
  
  #comments for books & authors
  def comments
    type = params[:type].constantize
    object = type.find(params[:id])
    @comment = object.comments.build(params[:comment])
    if @comment.save
      if type.to_s == 'Book'
        redirect_to book_path(object), :notice => 'Comment posted successfully'
      elsif type.to_s == 'Author'
        redirect_to author_book_path(object), :notice => 'Comment posted successfully'
      end
    else
      if @comment.errors[:comment]
        if type.to_s == 'Book'
          redirect_to book_path(object), :notice => '1 error prohibited this comment from being saved: ' + @comment.errors.full_messages.join(",")
        elsif type.to_s == 'Author'
          redirect_to author_book_path(object), :notice => '1 error prohibited this comment from being saved: ' + @comment.errors.full_messages.join(",")
        end
      else
        render :text => 'Something went wrong'
      end
    end
  end  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment_form.html.erb
<%=render :partial => 'shared/error_messages', :locals => {:object => @comment}%>
<div class="actions">
    <%= text_area :comment, :comment, {:size => '70x3'} %>
    <%= submit_tag "Post" %>
</div>

app/views/books/_form.html.erb
<%=render :partial => 'shared/error_messages', :locals => {:object => @book}%>
<%= form_for(@book) do |f| %>
  <div class="actions">
  	Name:&nbsp;&nbsp;&nbsp;
  	<%= f.text_field :name%>
	<br/>
	<br/>
	Authors:&nbsp;&nbsp;
	<%= f.text_field :author_names%>
	(Please enter multiple authors separated by comma only)
	<br/>
	<br/>
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/books/author.html.erb
<p id="notice"><%= notice %></p>
<%=@author.name%>
<br/>
<%=@comments.length%> Comments
<br/><br/>
<%for comment in @comments%>
	<strong><%=comment.comment%></strong><br/>
	Posted <%=comment.created_at.strftime("%b %d, %Y at %I:%M %p")%><br/>
	<%=comment.user.email%><br/> 
	<br/>
<%end%>

<%@comment = Comment.new%>
<%= form_for @comment, :url => comments_books_path(:id => @author.id, :type => 'Author'), :method => :post do |f| %>
	<%= render 'comment_form' %>
<%end%>
<%= link_to 'Back', authors_books_path %>

app/views/books/authors.html.erb
<h1>Listing authors</h1>

<table>
<% @authors.each do |author| %>
  <tr>
  	<td><%=author.name%></td>
	<td><%= link_to 'Show', author_book_path(author) %></td>
  </tr>
<% end %>
</table>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
<% @books.each do |book| %>
  <tr>
  	<td><%=book.name%></td>
    <td><%= link_to 'Show', book %></td>
    <td><%# link_to 'Edit', edit_book_path(book) %></td>
    <td><%# link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%if current_user.role? 'Admin User'%>
<%= link_to 'New Book', new_book_path %>
<%end%>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<%=@book.name%>
<br/>
<%=(@authors.collect{|a| a.name}).join(" , ")%>
<br/>
<br/>
<%=@comments.length%> Comments
<br/><br/>
<%for comment in @comments%>
	<strong><%=comment.comment%></strong><br/>
	Posted <%=comment.created_at.strftime("%b %d, %Y at %I:%M %p")%><br/>
	<%=comment.user.email%><br/> 
	<br/>
<%end%>

<%@comment = Comment.new%>
<%= form_for @comment, :url => comments_books_path(:id => @book.id, :type => 'Book'), :method => :post do |f| %>
	<%= render 'comment_form' %>
<%end%>
<%# link_to 'Edit', edit_book_path(@book) %>
<%= link_to 'Back', books_path %>